name: derpflegerspricht
favicon: null
layout_spectrum: 0
typography_spectrum: 0.39149
title: 'Es ist nicht wichtig was Du sagst, sondern wie'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c7c7c7'
    - '#dc2829'
    - '#777777'
    - '#f2f2f2'
    - '#383838'
  brandStrength: 0.6314600778277963
  lightness: 0.34211031370796263
  saturation: 0.2737065034452826
  rhythmicContrast: 0.8492272337898612
purpose: []
